// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: node.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NodeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid       string      `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	SystemInfo *SystemInfo `protobuf:"bytes,2,opt,name=systemInfo,proto3" json:"systemInfo,omitempty"`
	IpAddr     string      `protobuf:"bytes,3,opt,name=IpAddr,proto3" json:"IpAddr,omitempty"`
	Network    string      `protobuf:"bytes,4,opt,name=Network,proto3" json:"Network,omitempty"`
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConfig) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *NodeConfig) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *NodeConfig) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *NodeConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type SystemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sysinfo *SystemInfo_SYSINFO   `protobuf:"bytes,1,opt,name=sysinfo,proto3" json:"sysinfo,omitempty"`
	Node    *SystemInfo_NODE      `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Os      *SystemInfo_OS        `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Kernel  *SystemInfo_KERNEL    `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Product *SystemInfo_PRODUCT   `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	Board   *SystemInfo_BOARD     `protobuf:"bytes,6,opt,name=board,proto3" json:"board,omitempty"`
	Chassis *SystemInfo_CHASSIS   `protobuf:"bytes,7,opt,name=chassis,proto3" json:"chassis,omitempty"`
	Bios    *SystemInfo_BIOS      `protobuf:"bytes,8,opt,name=bios,proto3" json:"bios,omitempty"`
	Cpu     *SystemInfo_CPU       `protobuf:"bytes,9,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory  *SystemInfo_MEMORY    `protobuf:"bytes,10,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage []*SystemInfo_STORAGE `protobuf:"bytes,11,rep,name=storage,proto3" json:"storage,omitempty"`
	Network []*SystemInfo_NETWORK `protobuf:"bytes,12,rep,name=network,proto3" json:"network,omitempty"`
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetSysinfo() *SystemInfo_SYSINFO {
	if x != nil {
		return x.Sysinfo
	}
	return nil
}

func (x *SystemInfo) GetNode() *SystemInfo_NODE {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *SystemInfo) GetOs() *SystemInfo_OS {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *SystemInfo) GetKernel() *SystemInfo_KERNEL {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *SystemInfo) GetProduct() *SystemInfo_PRODUCT {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *SystemInfo) GetBoard() *SystemInfo_BOARD {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *SystemInfo) GetChassis() *SystemInfo_CHASSIS {
	if x != nil {
		return x.Chassis
	}
	return nil
}

func (x *SystemInfo) GetBios() *SystemInfo_BIOS {
	if x != nil {
		return x.Bios
	}
	return nil
}

func (x *SystemInfo) GetCpu() *SystemInfo_CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemInfo) GetMemory() *SystemInfo_MEMORY {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemInfo) GetStorage() []*SystemInfo_STORAGE {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *SystemInfo) GetNetwork() []*SystemInfo_NETWORK {
	if x != nil {
		return x.Network
	}
	return nil
}

type SystemInfo_SYSINFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SystemInfo_SYSINFO) Reset() {
	*x = SystemInfo_SYSINFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_SYSINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_SYSINFO) ProtoMessage() {}

func (x *SystemInfo_SYSINFO) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_SYSINFO.ProtoReflect.Descriptor instead.
func (*SystemInfo_SYSINFO) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SystemInfo_SYSINFO) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo_SYSINFO) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SystemInfo_NODE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname  string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Machineid string `protobuf:"bytes,2,opt,name=machineid,proto3" json:"machineid,omitempty"`
	Timezone  string `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *SystemInfo_NODE) Reset() {
	*x = SystemInfo_NODE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_NODE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_NODE) ProtoMessage() {}

func (x *SystemInfo_NODE) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_NODE.ProtoReflect.Descriptor instead.
func (*SystemInfo_NODE) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SystemInfo_NODE) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo_NODE) GetMachineid() string {
	if x != nil {
		return x.Machineid
	}
	return ""
}

func (x *SystemInfo_NODE) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type SystemInfo_OS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor       string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Version      string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Release      string `protobuf:"bytes,4,opt,name=release,proto3" json:"release,omitempty"`
	Architecture string `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
}

func (x *SystemInfo_OS) Reset() {
	*x = SystemInfo_OS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_OS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_OS) ProtoMessage() {}

func (x *SystemInfo_OS) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_OS.ProtoReflect.Descriptor instead.
func (*SystemInfo_OS) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 2}
}

func (x *SystemInfo_OS) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemInfo_OS) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *SystemInfo_OS) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo_OS) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *SystemInfo_OS) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type SystemInfo_KERNEL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Release      string `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Version      string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Architecture string `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
}

func (x *SystemInfo_KERNEL) Reset() {
	*x = SystemInfo_KERNEL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_KERNEL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_KERNEL) ProtoMessage() {}

func (x *SystemInfo_KERNEL) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_KERNEL.ProtoReflect.Descriptor instead.
func (*SystemInfo_KERNEL) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 3}
}

func (x *SystemInfo_KERNEL) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *SystemInfo_KERNEL) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo_KERNEL) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type SystemInfo_PRODUCT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
}

func (x *SystemInfo_PRODUCT) Reset() {
	*x = SystemInfo_PRODUCT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_PRODUCT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_PRODUCT) ProtoMessage() {}

func (x *SystemInfo_PRODUCT) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_PRODUCT.ProtoReflect.Descriptor instead.
func (*SystemInfo_PRODUCT) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 4}
}

func (x *SystemInfo_PRODUCT) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemInfo_PRODUCT) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

type SystemInfo_BOARD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor  string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SystemInfo_BOARD) Reset() {
	*x = SystemInfo_BOARD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_BOARD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_BOARD) ProtoMessage() {}

func (x *SystemInfo_BOARD) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_BOARD.ProtoReflect.Descriptor instead.
func (*SystemInfo_BOARD) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 5}
}

func (x *SystemInfo_BOARD) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemInfo_BOARD) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *SystemInfo_BOARD) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SystemInfo_CHASSIS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   float64 `protobuf:"fixed64,1,opt,name=type,proto3" json:"type,omitempty"`
	Vendor string  `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
}

func (x *SystemInfo_CHASSIS) Reset() {
	*x = SystemInfo_CHASSIS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_CHASSIS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_CHASSIS) ProtoMessage() {}

func (x *SystemInfo_CHASSIS) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_CHASSIS.ProtoReflect.Descriptor instead.
func (*SystemInfo_CHASSIS) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 6}
}

func (x *SystemInfo_CHASSIS) GetType() float64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SystemInfo_CHASSIS) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

type SystemInfo_BIOS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vendor  string `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Date    string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *SystemInfo_BIOS) Reset() {
	*x = SystemInfo_BIOS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_BIOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_BIOS) ProtoMessage() {}

func (x *SystemInfo_BIOS) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_BIOS.ProtoReflect.Descriptor instead.
func (*SystemInfo_BIOS) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 7}
}

func (x *SystemInfo_BIOS) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *SystemInfo_BIOS) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo_BIOS) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SystemInfo_CPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vendor  string  `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model   string  `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Cache   float64 `protobuf:"fixed64,3,opt,name=cache,proto3" json:"cache,omitempty"`
	Cpus    float64 `protobuf:"fixed64,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Cores   float64 `protobuf:"fixed64,5,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads float64 `protobuf:"fixed64,6,opt,name=threads,proto3" json:"threads,omitempty"`
}

func (x *SystemInfo_CPU) Reset() {
	*x = SystemInfo_CPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_CPU) ProtoMessage() {}

func (x *SystemInfo_CPU) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_CPU.ProtoReflect.Descriptor instead.
func (*SystemInfo_CPU) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 8}
}

func (x *SystemInfo_CPU) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *SystemInfo_CPU) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SystemInfo_CPU) GetCache() float64 {
	if x != nil {
		return x.Cache
	}
	return 0
}

func (x *SystemInfo_CPU) GetCpus() float64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *SystemInfo_CPU) GetCores() float64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *SystemInfo_CPU) GetThreads() float64 {
	if x != nil {
		return x.Threads
	}
	return 0
}

type SystemInfo_MEMORY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SystemInfo_MEMORY) Reset() {
	*x = SystemInfo_MEMORY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_MEMORY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_MEMORY) ProtoMessage() {}

func (x *SystemInfo_MEMORY) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_MEMORY.ProtoReflect.Descriptor instead.
func (*SystemInfo_MEMORY) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 9}
}

type SystemInfo_STORAGE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Model  string  `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Serial string  `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Size   float64 `protobuf:"fixed64,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SystemInfo_STORAGE) Reset() {
	*x = SystemInfo_STORAGE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_STORAGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_STORAGE) ProtoMessage() {}

func (x *SystemInfo_STORAGE) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_STORAGE.ProtoReflect.Descriptor instead.
func (*SystemInfo_STORAGE) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 10}
}

func (x *SystemInfo_STORAGE) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemInfo_STORAGE) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SystemInfo_STORAGE) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *SystemInfo_STORAGE) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SystemInfo_NETWORK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver     string `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Macaddress string `protobuf:"bytes,3,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
}

func (x *SystemInfo_NETWORK) Reset() {
	*x = SystemInfo_NETWORK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo_NETWORK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo_NETWORK) ProtoMessage() {}

func (x *SystemInfo_NETWORK) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo_NETWORK.ProtoReflect.Descriptor instead.
func (*SystemInfo_NETWORK) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 11}
}

func (x *SystemInfo_NETWORK) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemInfo_NETWORK) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *SystemInfo_NETWORK) GetMacaddress() string {
	if x != nil {
		return x.Macaddress
	}
	return ""
}

var File_node_proto protoreflect.FileDescriptor

var file_node_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x70, 0x41, 0x64, 0x64,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0xba, 0x0c, 0x0a, 0x0a,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x07, 0x73, 0x79,
	0x73, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53,
	0x59, 0x53, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x73, 0x79, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x2a, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x4e, 0x4f, 0x44, 0x45, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x02, 0x6f,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4f, 0x53, 0x52, 0x02, 0x6f,
	0x73, 0x12, 0x30, 0x0a, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4b, 0x45, 0x52, 0x4e, 0x45, 0x4c, 0x52, 0x06, 0x6b, 0x65, 0x72,
	0x6e, 0x65, 0x6c, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x42, 0x4f, 0x41, 0x52, 0x44,
	0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x73, 0x73,
	0x69, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x48, 0x41, 0x53,
	0x53, 0x49, 0x53, 0x52, 0x07, 0x63, 0x68, 0x61, 0x73, 0x73, 0x69, 0x73, 0x12, 0x2a, 0x0a, 0x04,
	0x62, 0x69, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x42, 0x49,
	0x4f, 0x53, 0x52, 0x04, 0x62, 0x69, 0x6f, 0x73, 0x12, 0x27, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x50, 0x55, 0x52, 0x03, 0x63, 0x70,
	0x75, 0x12, 0x30, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x52,
	0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4e, 0x45, 0x54,
	0x57, 0x4f, 0x52, 0x4b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x1a, 0x41, 0x0a,
	0x07, 0x53, 0x59, 0x53, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x1a, 0x5c, 0x0a, 0x04, 0x4e, 0x4f, 0x44, 0x45, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x1a, 0x88,
	0x01, 0x0a, 0x02, 0x4f, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x60, 0x0a, 0x06, 0x4b, 0x45, 0x52,
	0x4e, 0x45, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x35, 0x0a, 0x07, 0x50,
	0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x1a, 0x4d, 0x0a, 0x05, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x1a, 0x35, 0x0a, 0x07, 0x43, 0x48, 0x41, 0x53, 0x53, 0x49, 0x53, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x1a, 0x4c, 0x0a, 0x04, 0x42, 0x49, 0x4f, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x8d, 0x01, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x70, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x63, 0x70, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x74,
	0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x1a, 0x08, 0x0a, 0x06, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59,
	0x1a, 0x5f, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x1a, 0x55, 0x0a, 0x07, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x63, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61,
	0x63, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData = file_node_proto_rawDesc
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_proto_rawDescData)
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_node_proto_goTypes = []interface{}{
	(*NodeConfig)(nil),         // 0: proto.NodeConfig
	(*SystemInfo)(nil),         // 1: proto.SystemInfo
	(*SystemInfo_SYSINFO)(nil), // 2: proto.SystemInfo.SYSINFO
	(*SystemInfo_NODE)(nil),    // 3: proto.SystemInfo.NODE
	(*SystemInfo_OS)(nil),      // 4: proto.SystemInfo.OS
	(*SystemInfo_KERNEL)(nil),  // 5: proto.SystemInfo.KERNEL
	(*SystemInfo_PRODUCT)(nil), // 6: proto.SystemInfo.PRODUCT
	(*SystemInfo_BOARD)(nil),   // 7: proto.SystemInfo.BOARD
	(*SystemInfo_CHASSIS)(nil), // 8: proto.SystemInfo.CHASSIS
	(*SystemInfo_BIOS)(nil),    // 9: proto.SystemInfo.BIOS
	(*SystemInfo_CPU)(nil),     // 10: proto.SystemInfo.CPU
	(*SystemInfo_MEMORY)(nil),  // 11: proto.SystemInfo.MEMORY
	(*SystemInfo_STORAGE)(nil), // 12: proto.SystemInfo.STORAGE
	(*SystemInfo_NETWORK)(nil), // 13: proto.SystemInfo.NETWORK
}
var file_node_proto_depIdxs = []int32{
	1,  // 0: proto.NodeConfig.systemInfo:type_name -> proto.SystemInfo
	2,  // 1: proto.SystemInfo.sysinfo:type_name -> proto.SystemInfo.SYSINFO
	3,  // 2: proto.SystemInfo.node:type_name -> proto.SystemInfo.NODE
	4,  // 3: proto.SystemInfo.os:type_name -> proto.SystemInfo.OS
	5,  // 4: proto.SystemInfo.kernel:type_name -> proto.SystemInfo.KERNEL
	6,  // 5: proto.SystemInfo.product:type_name -> proto.SystemInfo.PRODUCT
	7,  // 6: proto.SystemInfo.board:type_name -> proto.SystemInfo.BOARD
	8,  // 7: proto.SystemInfo.chassis:type_name -> proto.SystemInfo.CHASSIS
	9,  // 8: proto.SystemInfo.bios:type_name -> proto.SystemInfo.BIOS
	10, // 9: proto.SystemInfo.cpu:type_name -> proto.SystemInfo.CPU
	11, // 10: proto.SystemInfo.memory:type_name -> proto.SystemInfo.MEMORY
	12, // 11: proto.SystemInfo.storage:type_name -> proto.SystemInfo.STORAGE
	13, // 12: proto.SystemInfo.network:type_name -> proto.SystemInfo.NETWORK
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_SYSINFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_NODE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_OS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_KERNEL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_PRODUCT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_BOARD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_CHASSIS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_BIOS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_CPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_MEMORY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_STORAGE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo_NETWORK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_rawDesc = nil
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
